spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demoDB;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: dev,test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true

server:
  port: 8081